import { Search, Sparkles } from "lucide-react";

// Mock data agar kode lebih rapi
const mockups = [
  {
    id: 1,
    title: "Premium Chips",
    tag: "Artisan Snack",
    bg: "bg-amber-100/50",
  },
  { id: 2, title: "Gourmet Box", tag: "Craft Box", bg: "bg-stone-200/50" },
  {
    id: 3,
    title: "Tropical Fruit",
    tag: "Vibrant Pouch",
    bg: "bg-orange-100/50",
  },
  {
    id: 4,
    title: "Luxury Chocolate",
    tag: "Dark Minimalist",
    bg: "bg-zinc-100",
  },
  { id: 5, title: "Artisan Cookies", tag: "Window Pouch", bg: "bg-amber-50" },
  { id: 6, title: "Matcha Green", tag: "Fresh Stand-up", bg: "bg-green-50" },
];

export default function ExploreGallery() {
  return (
    <section className="max-w-7xl mx-auto px-6 py-20">
      <div className="text-center mb-12">
        <h2 className="text-3xl font-bold text-gray-900 mb-4 inline-flex items-center gap-2">
          <Sparkles className="w-6 h-6 text-amber-500" />
          Explore AI-Generated Styles
          <Sparkles className="w-6 h-6 text-amber-500" />
        </h2>
        <p className="text-gray-500">
          Discover stunning packaging ideas generated by our LoRA models.
        </p>
      </div>

      {/* Search & Filters */}
      <div className="max-w-2xl mx-auto flex flex-col gap-6 mb-12">
        <div className="relative">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
          <input
            type="text"
            placeholder="Search prompt or style..."
            className="w-full pl-12 pr-4 py-4 rounded-full border border-gray-200 bg-white shadow-sm focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-500 transition"
          />
        </div>

        <div className="flex flex-wrap items-center justify-center gap-3">
          {[
            "All",
            "Food & Beverages",
            "Artisan Snacks",
            "Modern Minimalist",
            "Traditional",
          ].map((filter, i) => (
            <button
              key={i}
              className={`px-5 py-2 rounded-full text-sm font-medium transition ${
                i === 0
                  ? "bg-zinc-900 text-white"
                  : "bg-white border border-gray-200 text-gray-600 hover:bg-gray-50"
              }`}
            >
              {filter}
            </button>
          ))}
        </div>
      </div>

      {/* Grid Gallery */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {mockups.map((item) => (
          <div key={item.id} className="group cursor-pointer">
            <div
              className={`w-full aspect-[4/5] ${item.bg} rounded-3xl mb-4 overflow-hidden relative border border-gray-100 transition duration-300 group-hover:shadow-xl group-hover:-translate-y-1`}
            >
              {/* Tempat Image asli dari Next/Image diletakkan di sini nantinya */}
            </div>
            <div>
              <h3 className="text-lg font-semibold text-gray-900">
                {item.title}
              </h3>
              <p className="text-sm text-gray-500">{item.tag}</p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
